void move_cursor_up(int);
void move_cursor_down(int);
void move_cursor_forward(int);
void move_cursor_back(int);
void earse_display(int);
void earse_entire_display();
void earse_in_line(int);
void earse_entire_line();
void set_cursor_position(int, int);
void reset_cursor_position();
